name: auto Trigger Example
on: push 


jobs:
  say-hello:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Say Hello
      run: echo "Hello from a auto triggered workflow!"


