name: auto Trigger Example
on: push 


jobs:
  say-hello:
    

    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.2.2
    - name: list files
      run: ls
    - name: give perm
      run: chmod +x script.sh
    - name: install cowsay program
      run: ./script.sh


