name: auto Trigger Example
on: push 


jobs:
  say-hello:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
   
    runs-on: ${{matrix.os}}
    steps:
    - name: run docker
      uses: docker/setup-docker-action@feature
    - name: run image
      run: docker info
    - name: run image
      run: docker run hello-world

