name: auto Trigger Example
on: push 


jobs:
  say-hello:
    
   
    runs-on: ubuntu-latest
    steps:
    - name: run docker
      uses: docker/setup-docker-action@feature
    - name: run image
      run: docker info
    - name: run image
      run: docker run hello-world

